### ISSUE TITLE
[Windows] Cannot Delete or Edit Note Immediately After Creation 'Because it is Being Used by Another Process'

### ISSUE THREAD

**Issue by MicahClarkeR** [candlebrae/pluralnotes#2]
When logging in and creating a file, and immediately deleting it this will cause PluralNotes to crash with the following error. Also if a file is immediately created, then saved, then attempted to be edited this will cause Notepad to not be able to overwrite the note file.

This could be releated to the note file not being created seemingly by PluralNotes, Notebad warns the file isn't created, and prompts user if they want to create the file (see below).

Issue when using the code found in #1 - required to get PluralNotes working on Windows - but I think this might be an issue with Notepad or the Python process keeping the file 'open' as recognised by Windows. Thus preventing deleting and editing.

![notepad-create-file](https://user-images.githubusercontent.com/71971561/129492904-143daade-4539-421b-b890-d6710097cc8f.png)

Error:
```Traceback (most recent call last):
File "F:\Git Repositories\PluralNotes\pluralnotesapp.py", line 81, in <module>
  core.noteHandler(userDir)

File "F:\Git Repositories\PluralNotes\core.py", line 288, in noteHandler
  paginateDir(os.path.dirname)

File "F:\Git Repositories\PluralNotes\core.py", line 192, in paginateDir
  os.remove(deleteFile)

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'Test-2-2021-08-15.txt'

**Comment by candlebrae** [comment]
Can confirm this is a Windows-specific error, as I can't replicate this on Linux. Does this only happen with the most recently created note, or does it affect more than one note? Does the error happen when the note is signed, unsigned, or both?

Could you try to replicate the error using a different editor to determine if the issue is specific to Notepad?

**Comment by candlebrae** [comment]
Pushed a possible fix; added a close() for newly-made files after they're done being edited. No idea if this will work, but it might. Let me know if this resolves the issue.

**Comment by MicahClarkeR** [comment]
I had a toy around and I think that this has been fixed by adding the 'close' and changing the mode used to open the new note.
